[package]
name = "select-sort"
version = "0.1.0"
authors = ["tranxuanthang <tran.xuan.thangb@sun-asterisk.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
